
# Check for an interactive session
[ -z "$PS1" ] && return

alias ls='ls --color=auto'
alias ll='ls -l -S -h'
alias pss='ps aux|grep'
PS1='[\u@\h \W]\$ '
#PS1='\u \W>'
export EDITOR=vim

complete -cf sudo
source /home/gl/configs/bin/git-completion.bash
source /home/gl/configs/bin/hg_bash_completion
source /home/gl/configs/bin/bash_completion_tmux.sh

