
# Check for an interactive session
[ -z "$PS1" ] && return

alias ls='ls --color=auto'
alias ll='ls -l -S -h'
alias pss='ps aux|grep'
PS1='[\u@\h \W]\$ '
#PS1='\u \W>'
export EDITOR=vim

complete -cf sudo
